### ISSUE TITLE
Cannot claim new printer

### ISSUE THREAD

**Issue by sarahkadar** [nordprojects/sirius#15]
1. go to https://little-printer-claim-code.netlify.app/
2. copy the claim code
3. go to http://littleprinter.nordprojects.co/
4. enter the claim code, give it a name, press "Claim printer"
5. You're redirected to the home page and the printer is not added; no error message is displayed.

**Comment by joerick** [comment]
Afraid I don't know how the little-printer-claim-code site works, but fake printers still work on the server-

```bash
joerick@joerick3 ~/P/sirius> heroku run bash                        130 master?
Running bash on ⬢ nord-sirius... up, run.6661 (Hobby)
~ $ ./manage.py fake printer
/app/sirius/emulate/commands.py:8: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util.ssl_ (/app/.heroku/python/lib/python3.7/site-packages/urllib3/util/ssl_.py)', 'urllib3.util (/app/.heroku/python/lib/python3.7/site-packages/urllib3/util/__init__.py)']. 
  gevent.monkey.patch_all()
[2020-05-10 11:13:11,045] DEBUG in webapp: Creating app.
DEBUG:sirius.web.webapp:Creating app.
     address: 18252e3bd7249cc2
       DB id: 323
      secret: a5d1bb83a9
         xor: 487148
  claim code: 234b-cnev-hfnh-fvqd

Created printer and saved as 18252e3bd7249cc2.printer
```

I've added this to the site and it's showing up as a new printer.

I did push some changes a couple of weeks back but it didn't change the claim logic - https://github.com/nordprojects/sirius/compare/e5adbc4b...nordprojects:master

**Comment by sarahkadar** [comment]
@joerick well, it may be in the server but sure not on the UI, I tried two printers already and yet I only see my real fake printer
<img width="270" alt="Screenshot 2020-05-10 13 20 18" src="https://user-images.githubusercontent.com/48946/81497797-1660af80-92c1-11ea-9406-aa069e67e96b.png">

**Comment by sarahkadar** [comment]
(the source for the site: https://github.com/notjosh/little-printer-claim-code-web, @notjosh  ported the printer generation logic to javascript)

**Comment by joerick** [comment]
(complete guess from reading the server code) try to have your fake printer connect to the server, then perform the claim

**Comment by sarahkadar** [comment]
@joerick I tried, and this happens:

```
root@raspi4 ~/sirius-client# ts-node bin/client.ts
Contacting wss://littleprinter.nordprojects.co/api/v1/connection
     address: 0aaab8e735e378b4
      secret: 13382744232
  claim code: zmkh-67ed-g2nf-6y40
-----------------------------
connecting to wss://littleprinter.nordprojects.co/api/v1/connection as: bridge: 2922fc8781b58000, device: 0aaab8e735e378b4
upgrade
open
Asked for encryption key
Asked for encryption key
Asked for encryption key
Asked for encryption key
Asked for encryption key
Asked for encryption key
Asked for encryption key
```

And it does not show up in the UI.

**Comment by sarahkadar** [comment]
@joerick tried claiming the printer again, still nothing.

**Comment by joerick** [comment]
@notjosh might be able to shed some light? I haven't used the fake printers at all tbh

**Comment by sarahkadar** [comment]
I'll try to create a new printer from `sirius` but I don't think @notjosh 's algo is in the wrong here.

**Comment by KTamas** [comment]
@joerick i'm trying to get sirius to work but i get a 'database does not exist' error

```
ktamas@ktmbp ~/Prog/sirius (master) [1]> docker-compose -f docker-compose.yml -f docker-compose.db.yml -f docker-compose.development.yml up
sirius_sirius-database_1 is up-to-date
Creating sirius_sirius-web_1 ... done
Creating sirius_sirius_1     ... done
Attaching to sirius_sirius-database_1, sirius_sirius-web_1, sirius_sirius_1
sirius-web_1       | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
sirius-web_1       | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
sirius-web_1       | forego     | starting dockergen.1 on port 5000
sirius-web_1       | forego     | starting nginx.1 on port 5100
sirius-web_1       | dockergen.1 | 2020/05/10 12:31:54 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
sirius-web_1       | dockergen.1 | 2020/05/10 12:31:54 Running 'nginx -s reload'
sirius-web_1       | dockergen.1 | 2020/05/10 12:31:54 Watching docker events
sirius-database_1  |
sirius-database_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
sirius-database_1  |
sirius-database_1  | 2020-05-10 12:28:30.987 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
sirius-database_1  | 2020-05-10 12:28:30.988 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
sirius-database_1  | 2020-05-10 12:28:30.988 UTC [1] LOG:  listening on IPv6 address "::", port 5432
sirius-database_1  | 2020-05-10 12:28:30.992 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
sirius-database_1  | 2020-05-10 12:28:31.019 UTC [25] LOG:  database system was shut down at 2020-04-18 15:31:27 UTC
sirius-database_1  | 2020-05-10 12:28:31.038 UTC [1] LOG:  database system is ready to accept connections
sirius-database_1  | 2020-05-10 12:28:31.366 UTC [32] LOG:  incomplete startup packet
sirius-database_1  | 2020-05-10 12:28:32.862 UTC [33] FATAL:  database "sirius-dev" does not exist
sirius-database_1  | 2020-05-10 12:29:14.306 UTC [1] LOG:  received smart shutdown request
sirius-database_1  | 2020-05-10 12:29:14.311 UTC [1] LOG:  background worker "logical replication launcher" (PID 31) exited with exit code 1
sirius-database_1  | 2020-05-10 12:29:14.312 UTC [26] LOG:  shutting down
sirius-database_1  | 2020-05-10 12:29:14.332 UTC [1] LOG:  database system is shut down
sirius-database_1  |
sirius-database_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
sirius-database_1  |
sirius-database_1  | 2020-05-10 12:29:21.305 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
sirius-database_1  | 2020-05-10 12:29:21.306 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
sirius-database_1  | 2020-05-10 12:29:21.306 UTC [1] LOG:  listening on IPv6 address "::", port 5432
sirius-database_1  | 2020-05-10 12:29:21.308 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
sirius-database_1  | 2020-05-10 12:29:21.326 UTC [25] LOG:  database system was shut down at 2020-05-10 12:29:14 UTC
sirius-database_1  | 2020-05-10 12:29:21.333 UTC [1] LOG:  database system is ready to accept connections
sirius-database_1  | 2020-05-10 12:29:21.723 UTC [32] LOG:  incomplete startup packet
sirius-database_1  | 2020-05-10 12:29:22.792 UTC [33] FATAL:  database "sirius-dev" does not exist
sirius-database_1  | 2020-05-10 12:29:48.018 UTC [1] LOG:  received smart shutdown request
sirius-database_1  | 2020-05-10 12:29:48.023 UTC [1] LOG:  background worker "logical replication launcher" (PID 31) exited with exit code 1
sirius-database_1  | 2020-05-10 12:29:48.025 UTC [26] LOG:  shutting down
sirius-database_1  | 2020-05-10 12:29:48.044 UTC [1] LOG:  database system is shut down
sirius-database_1  |
sirius-database_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
sirius-database_1  |
sirius-database_1  | 2020-05-10 12:30:01.993 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
sirius-database_1  | 2020-05-10 12:30:01.997 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
sirius-database_1  | 2020-05-10 12:30:01.997 UTC [1] LOG:  listening on IPv6 address "::", port 5432
sirius-database_1  | 2020-05-10 12:30:02.003 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
sirius-database_1  | 2020-05-10 12:30:02.031 UTC [26] LOG:  database system was shut down at 2020-05-10 12:29:48 UTC
sirius-database_1  | 2020-05-10 12:30:02.037 UTC [1] LOG:  database system is ready to accept connections
sirius-database_1  | 2020-05-10 12:30:02.361 UTC [33] LOG:  incomplete startup packet
sirius-database_1  | 2020-05-10 12:30:04.038 UTC [34] FATAL:  database "sirius-dev" does not exist
sirius-database_1  | 2020-05-10 12:30:28.199 UTC [35] FATAL:  database "sirius-dev" does not exist
sirius_1           | wait-for-it.sh: waiting 15 seconds for sirius-database:5432
sirius-database_1  | 2020-05-10 12:31:54.618 UTC [56] LOG:  incomplete startup packet
sirius_1           | wait-for-it.sh: sirius-database:5432 is available after 0 seconds
sirius_1           | Apply database migrations
sirius-web_1       | dockergen.1 | 2020/05/10 12:31:54 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
sirius-web_1       | dockergen.1 | 2020/05/10 12:31:54 Received event start for container f0bad55ccdec
sirius-web_1       | dockergen.1 | 2020/05/10 12:31:54 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
sirius_1           | /sirius/sirius/emulate/commands.py:8: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util (/usr/local/lib/python3.7/site-packages/urllib3/util/__init__.py)', 'urllib3.util.ssl_ (/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py)'].
sirius_1           |   gevent.monkey.patch_all()
sirius_1           | [2020-05-10 12:31:55,671] DEBUG in webapp: Creating app.
sirius_1           | DEBUG:sirius.web.webapp:Creating app.
sirius_1           | Importing environment from .env...
sirius-database_1  | 2020-05-10 12:31:55.725 UTC [57] FATAL:  database "sirius-dev" does not exist
sirius_1           | Traceback (most recent call last):
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
sirius_1           |     return fn()
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
sirius_1           |     return _ConnectionFairy._checkout(self)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
sirius_1           |     fairy = _ConnectionRecord.checkout(pool)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
sirius_1           |     rec = pool._do_get()
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
sirius_1           |     return self._create_connection()
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
sirius_1           |     return _ConnectionRecord(self)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
sirius_1           |     self.__connect(first_connect_check=True)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
sirius_1           |     connection = pool._invoke_creator(self)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
sirius_1           |     return dialect.connect(*cargs, **cparams)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 453, in connect
sirius_1           |     return self.dbapi.connect(*cargs, **cparams)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
sirius_1           |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sirius_1           | psycopg2.OperationalError: FATAL:  database "sirius-dev" does not exist
sirius_1           |
sirius_1           |
sirius_1           | The above exception was the direct cause of the following exception:
sirius_1           |
sirius_1           | Traceback (most recent call last):
sirius_1           |   File "manage.py", line 44, in <module>
sirius_1           |     manager.run()
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/flask_script/__init__.py", line 417, in run
sirius_1           |     result = self.handle(argv[0], argv[1:])
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/flask_script/__init__.py", line 386, in handle
sirius_1           |     res = handle(*args, **config)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/flask_script/commands.py", line 216, in __call__
sirius_1           |     return self.run(*args, **kwargs)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
sirius_1           |     f(*args, **kwargs)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 280, in upgrade
sirius_1           |     command.upgrade(config, revision, sql=sql, tag=tag)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 279, in upgrade
sirius_1           |     script.run_env()
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 475, in run_env
sirius_1           |     util.load_python_file(self.dir, "env.py")
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
sirius_1           |     module = load_module_py(module_id, path)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 174, in load_module_py
sirius_1           |     spec.loader.exec_module(module)
sirius_1           |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
sirius_1           |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
sirius_1           |   File "migrations/env.py", line 72, in <module>
sirius_1           |     run_migrations_online()
sirius_1           |   File "migrations/env.py", line 57, in run_migrations_online
sirius_1           |     connection = engine.connect()
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2206, in connect
sirius_1           |     return self._connection_cls(self, **kwargs)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
sirius_1           |     else engine.raw_connection()
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2306, in raw_connection
sirius_1           |     self.pool.unique_connection, _connection
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
sirius_1           |     e, dialect, self
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
sirius_1           |     util.raise_from_cause(sqlalchemy_exception, exc_info)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
sirius_1           |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
sirius_1           |     raise value.with_traceback(tb)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
sirius_1           |     return fn()
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
sirius_1           |     return _ConnectionFairy._checkout(self)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
sirius_1           |     fairy = _ConnectionRecord.checkout(pool)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
sirius_1           |     rec = pool._do_get()
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
sirius_1           |     return self._create_connection()
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
sirius_1           |     return _ConnectionRecord(self)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
sirius_1           |     self.__connect(first_connect_check=True)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
sirius_1           |     connection = pool._invoke_creator(self)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
sirius_1           |     return dialect.connect(*cargs, **cparams)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 453, in connect
sirius_1           |     return self.dbapi.connect(*cargs, **cparams)
sirius_1           |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
sirius_1           |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sirius_1           | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "sirius-dev" does not exist
sirius_1           |
sirius_1           | (Background on this error at: http://sqlalche.me/e/e3q8)
sirius_1           | Starting server
```

**Comment by sarahkadar** [comment]
@joerick I take it back, it is something with @notjosh 's code. I made a printer from `sirius` with `manage.py` and that works.

**Comment by sarahkadar** [comment]
@joerick however, my local `sirius` instance gives me a 503 error.

**Comment by joerick** [comment]
did you manage to get anywhere further with this @KTamas ?

**Comment by notjosh** [comment]
Two things to add!

1. I fixed https://little-printer-claim-code.netlify.app/, since this ticket was created, as it was using the _address_ to make the claim code, not the _xor_. (Was a classic "tests from sirius are passing, this must work fine", doh 🤦). So the claim codes seem to work okay again now!
2. 503s happen for a few reasons silently, but show details in the logs. We should probably surfaced that error up to the user somehow. I was losing my mind when I was trying to claim a printer that had been previously claimed by another user - "503" with no message :<

**Comment by joerick** [comment]
Ah great! Thanks for the update. Do the 503s represent unhandled exceptions in the Python server or something else?

**Comment by notjosh** [comment]
Yeah, exactly that.

For example, [this snippet](https://github.com/nordprojects/sirius/blob/9b1ed4cd6f0139f8d2af3566a71b70d8228de977/sirius/models/user.py#L87-L89) causes a response like:

<img width="2002" alt="Messages Image(2667305189)" src="https://user-images.githubusercontent.com/33126/82159183-d4210a80-988c-11ea-9e77-f6163fc0af85.png">
